const moduleAlias = require('module-alias')
moduleAlias.addAlias('@', __dirname)
const Koa = require('koa')
const app = new Koa()
const bodyParser = require('koa-bodyparser')
const { createSocket } = require('@/utils/socket')
const { router } = require('./router/index')
require('./db')

app.use(bodyParser())
app.use(router.routes())
createSocket({ port: 6061 })
app.listen(6060, () => {
  console.log('6060start')
})
